//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProcessor {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locales() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupProcessor.Locales", typeof(Locales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please close or ignore active BF.
        /// </summary>
        internal static string active_bf {
            get {
                return ResourceManager.GetString("active_bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Adding infants....
        /// </summary>
        internal static string adding_infants {
            get {
                return ResourceManager.GetString("adding_infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Return to Smartpoint?.
        /// </summary>
        internal static string backToSmartpoint {
            get {
                return ResourceManager.GetString("backToSmartpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Booking file successfully created.
        /// </summary>
        internal static string bf_created {
            get {
                return ResourceManager.GetString("bf_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Closing Active Booking File.
        /// </summary>
        internal static string closing_bf {
            get {
                return ResourceManager.GetString("closing_bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Purging Active Booking File.
        /// </summary>
        internal static string closing_bf1 {
            get {
                return ResourceManager.GetString("closing_bf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Communication failure.
        /// </summary>
        internal static string comms_error {
            get {
                return ResourceManager.GetString("comms_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Creating Passive Segments for a Group.
        /// </summary>
        internal static string creating_bf {
            get {
                return ResourceManager.GetString("creating_bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný *** Finished ***.
        /// </summary>
        internal static string creating_finished {
            get {
                return ResourceManager.GetString("creating_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Continue with Passenger Names....
        /// </summary>
        internal static string creating_names {
            get {
                return ResourceManager.GetString("creating_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Default parameters used..
        /// </summary>
        internal static string ctrlfile_default {
            get {
                return ResourceManager.GetString("ctrlfile_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Following Control file will be created in your User profile:.
        /// </summary>
        internal static string ctrlfile_missing {
            get {
                return ResourceManager.GetString("ctrlfile_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný not found..
        /// </summary>
        internal static string ctrlfile_notfound {
            get {
                return ResourceManager.GetString("ctrlfile_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný    First application run.
        /// </summary>
        internal static string ctrlfile_warning {
            get {
                return ResourceManager.GetString("ctrlfile_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duplicated names.
        /// </summary>
        internal static string duplicated_names {
            get {
                return ResourceManager.GetString("duplicated_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No Text Data on the Clipboard.
        /// </summary>
        internal static string empty_clipboard {
            get {
                return ResourceManager.GetString("empty_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Really exit script?.
        /// </summary>
        internal static string exit_dialog {
            get {
                return ResourceManager.GetString("exit_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Extra name(s) listed.
        /// </summary>
        internal static string extra_names {
            get {
                return ResourceManager.GetString("extra_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Input Data.
        /// </summary>
        internal static string groupbox_editing {
            get {
                return ResourceManager.GetString("groupbox_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Host Communication.
        /// </summary>
        internal static string groupbox_terminal {
            get {
                return ResourceManager.GetString("groupbox_terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sending first Host Command.
        /// </summary>
        internal static string host_command {
            get {
                return ResourceManager.GetString("host_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Ignored flights: .
        /// </summary>
        internal static string ignored {
            get {
                return ResourceManager.GetString("ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Incomplete booking. Finalize BF manually, please..
        /// </summary>
        internal static string incomplete {
            get {
                return ResourceManager.GetString("incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Arrival.
        /// </summary>
        internal static string list_arr {
            get {
                return ResourceManager.GetString("list_arr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Class.
        /// </summary>
        internal static string list_class {
            get {
                return ResourceManager.GetString("list_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Date.
        /// </summary>
        internal static string list_date {
            get {
                return ResourceManager.GetString("list_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Day.
        /// </summary>
        internal static string list_day {
            get {
                return ResourceManager.GetString("list_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Departure.
        /// </summary>
        internal static string list_dep {
            get {
                return ResourceManager.GetString("list_dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Destination.
        /// </summary>
        internal static string list_dest {
            get {
                return ResourceManager.GetString("list_dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Flight number.
        /// </summary>
        internal static string list_flight {
            get {
                return ResourceManager.GetString("list_flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Origin.
        /// </summary>
        internal static string list_origin {
            get {
                return ResourceManager.GetString("list_origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pax.
        /// </summary>
        internal static string list_pax {
            get {
                return ResourceManager.GetString("list_pax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Status.
        /// </summary>
        internal static string list_status {
            get {
                return ResourceManager.GetString("list_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Terminal.
        /// </summary>
        internal static string list_terminal {
            get {
                return ResourceManager.GetString("list_terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing first name / gender.
        /// </summary>
        internal static string missing_firstname {
            get {
                return ResourceManager.GetString("missing_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing Group Name.
        /// </summary>
        internal static string missing_groupname {
            get {
                return ResourceManager.GetString("missing_groupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing Vendor Locator.
        /// </summary>
        internal static string missing_locator {
            get {
                return ResourceManager.GetString("missing_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing Passenger name(s).
        /// </summary>
        internal static string missing_names {
            get {
                return ResourceManager.GetString("missing_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Invalid Passenger Count.
        /// </summary>
        internal static string missing_paxnumber {
            get {
                return ResourceManager.GetString("missing_paxnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Viewpoint not configured on this machine.
        /// </summary>
        internal static string missing_viewpoint {
            get {
                return ResourceManager.GetString("missing_viewpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No valid flight(s) found.
        /// </summary>
        internal static string no_flights {
            get {
                return ResourceManager.GetString("no_flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing Host Command.
        /// </summary>
        internal static string no_hostCommand {
            get {
                return ResourceManager.GetString("no_hostCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Missing Phone Contact.
        /// </summary>
        internal static string no_phone {
            get {
                return ResourceManager.GetString("no_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Probably not a .
        /// </summary>
        internal static string no_pnr {
            get {
                return ResourceManager.GetString("no_pnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Booking not allowed. Switch to AG duty, please!.
        /// </summary>
        internal static string only_agent {
            get {
                return ResourceManager.GetString("only_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name List.
        /// </summary>
        internal static string pax_list {
            get {
                return ResourceManager.GetString("pax_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný result:.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sign into emulation please!.
        /// </summary>
        internal static string sem_fail {
            get {
                return ResourceManager.GetString("sem_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BF creation failure. Please ignore or complete BF manually..
        /// </summary>
        internal static string some_error {
            get {
                return ResourceManager.GetString("some_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Sign into Galileo please!.
        /// </summary>
        internal static string son_fail {
            get {
                return ResourceManager.GetString("son_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cannot proceed.
        /// </summary>
        internal static string unable {
            get {
                return ResourceManager.GetString("unable", resourceCulture);
            }
        }
    }
}
